---
title: "Resume"
---

###Jingwei Ren

615-586-7151           100 Haven Ave, New York, NY, 37235        jr3869@cumc.columbia.edu

####EDUCATION

Case Western Reserve University, Cleveland, Ohio                                                                                                                                        2014-2015

Bachelor of Science, Biochemistry                                                                                                                                                               GPA: 4.00/4.00

Vanderbilt University, Nashville, Tennessee                                                                                                                                                    2015-2018

Bachelor of Science, Math                                                                                                               GPA: 3.95/4.00

Bachelor of Science, Molecular and Cellular Biology.                                                                                                                              GPA: 3.867/4.00 Cumulative GPA: 3.83/4.00

Columbia University, New York, NY                                                                                                                                                      08.2018-present


####AWARDS, HONORS, ACHIEVEMENTS
Finalist in Vanderbilt University Health Case Competition 2017 (4th place out of 25 teams)

•	Collaborated in a four person group with Vanderbilt medical students and MPH graduates to formulate a plan for improving maternal health outcomes in Haiti by expanding access to safe surgery

Vanderbilt Dean’s List (2015-2017)

####WORK EXPERIENCE

Columbia University, New York, NY                                                                                                                                                     08.2018-Present

Research Assistant in Biomedical Informatics Department  

•	Designed web applications that facilitated predicting pathogenicity of variants by deep learning.
•	Predicted pathogenicity of rare noncoding variants based on post-transcriptional regulation with computational model using machine learning.

Vanderbilt University, Nashville, TN                                                                                                                                                     08.2017-01.2018

STEM Tutor

•	Taught students various engineering and science courses, such as math and basic science every weekday.
•	Developed mentorship skills and strengthened interpersonal and communicative skills.

Vanderbilt University, Nashville, TN                                                                                                                                                     08.2016-05.2018

Research Assistant in Biology Department   

•	Analyzed the relationship between zebrafish retina gene regeneration rates and fish age by applying different damage models.
•	Mastered lab techniques such as embryo injections, immunofluorescent staining and clustered regularly interspaced short palindromic repeats techniques in order to analyze mutations in fish genes and their relationship to tissue regeneration.

Vanderbilt University, Nashville, TN                                                                                                                                                     01.2016-05.2016

Research Assistant in diabetes center

•	Investigated compensatory responses of pancreatic alpha cells and beta cells by zebrafish modeling.
•	Conducted DNA cloning, sequencing, and mapping using polymerase chain reaction and gel electrophoresis. 

####VOLUNTEER EXPERIENCE

Nashville, TN, Hubert, NC                                                                                                                                                            Fall 2016, Spring 2017                                                                                                           
Alternative Spring, Thanksgiving and Winter break

•	Explored and tackled the problems of homelessness and poverty in Nashville by working with community organization professionals.
•	Combated the issues of animal welfare by offering rehabilitative care and medical treatments for the current wildlife. 

Vanderbilt University, Nashville, TN                                                                                                                            Fall 2016, Spring 2017-05.2018

Project Bridge 

•	Taught a Burmese family English weekly and helped them pass the citizen test 
•	Achieved the goal of improving the well-being of refugees and immigrants.

Vanderbilt University, Nashville, TN                                                                                                                                          Fall 2016, Spring 2017

Vanderbilt Volunteers for Science 

•	Taught middle school students inquiry-based, hands-on science modules in order to foster an interest in scientific fields.

####LEADERSHIP

Project Bridge Executive Board                                                                                                                                                           Fall 2016-05.2018

Secretary

•	Organized team planning and refugee partnerships to create the best English mentorship.
•	Provided student volunteers with a basic foundation and relevant training for working with multi-cultural populations. 

Vanderbilt ILEAD                                                                                                                                                                                 Fall 2017-05.2018

International orientation leader and mentor

•	Provided guidelines and mentoring to a group of eight freshman students during orientation week and throughout the whole semester.

####SKILLS
Language: Mandarin Chinese (native), Proficient with R studio, Mathematica, MATLAB, Microsoft Word, Powerpoint, Excel.  



